name: Build Skills

on:
  push:
    branches:
      - master
    paths:
      - '[0-9][0-9]-*/**'
      - 'build.py'
      - 'templates/**'
      - 'requirements.txt'
      - '.github/workflows/build-skills.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run build script
        run: |
          python build.py

      - name: Deploy to gh-pages branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Create orphan gh-pages branch if it doesn't exist
          git fetch origin gh-pages || git checkout --orphan gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove all files except docs/
          git rm -rf . || true
          git clean -fdx -e docs

          # Move docs contents to root
          if [ -d "docs" ]; then
            mv docs/* . || true
            mv docs/.* . 2>/dev/null || true
            rm -rf docs
          fi

          # Add and commit
          git add .
          git commit -m "Build skill packages from ${GITHUB_SHA::7}" || echo "No changes to commit"

          # Force push to gh-pages
          git push origin gh-pages --force
